name:                 haskell-connect4
version:              0.1.0.0
visibility:           public
id:                   haskell-connect4-0.1.0.0-inplace
key:                  haskell-connect4-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2026 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/haskell-connect4#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/haskell-connect4#readme>

abi:                  inplace
exposed:              True
exposed-modules:      Board Check InputHelper Logic
hidden-modules:       Paths_haskell_connect4
import-dirs:
    C:\Users\tjdor\git\haskell-connect4\dist-newstyle\build\x86_64-windows\ghc-9.6.7\haskell-connect4-0.1.0.0\build

library-dirs:
    C:\Users\tjdor\git\haskell-connect4\dist-newstyle\build\x86_64-windows\ghc-9.6.7\haskell-connect4-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    C:\Users\tjdor\git\haskell-connect4\dist-newstyle\build\x86_64-windows\ghc-9.6.7\haskell-connect4-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    C:\Users\tjdor\git\haskell-connect4\dist-newstyle\build\x86_64-windows\ghc-9.6.7\haskell-connect4-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

data-dir:             C:\Users\tjdor\git\haskell-connect4\.
hs-libraries:         HShaskell-connect4-0.1.0.0-inplace
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:              base-4.18.3.0
haddock-interfaces:
    C:\Users\tjdor\git\haskell-connect4\dist-newstyle\build\x86_64-windows\ghc-9.6.7\haskell-connect4-0.1.0.0\doc\html\haskell-connect4\haskell-connect4.haddock

haddock-html:
    C:\Users\tjdor\git\haskell-connect4\dist-newstyle\build\x86_64-windows\ghc-9.6.7\haskell-connect4-0.1.0.0\doc\html\haskell-connect4
